### ISSUE TITLE
Feature request: Schedule options for Pulse sample rate

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/pulse#307] opened 2024-02-05 16:15 UTC
Hi,

I'd like to request a new feature for the `sample_rate` config. In my application, I find that the majority of my requests happen during the daytime and between 5pm in the evening and 9am the next day. This means that I, right now, have to always have my sample rate set incredibly low: "0.025" to capture 2.5% of my entries, but during a less busy time, this number means accuracy goes out of the window.

Would it be possible to introduce a schedule option to check between times and perform a different sample rate to improve accuracy, for example:

The following...

```php
Recorders\CacheInteractions::class => [
    'enabled' => env('PULSE_CACHE_INTERACTIONS_ENABLED', true),
    'sample_rate' => env('PULSE_CACHE_INTERACTIONS_SAMPLE_RATE', 0.025),
    'ignore' => [
        ...Pulse::defaultVendorCacheKeys(),
    ],
    'groups' => [
        '/^job-exceptions:.*/' => 'job-exceptions:*',
        '/^health:checks:.*/' => 'health:checks:*',
        '/^laravel-health:check-.*/' => 'laravel-health:check:*',
        '/^dashboard_stats_.*/' => 'dashboard_stats_*',
        '/^archive:db:.*/' => 'archive:db:*',
        '/^setting_company_.*/' => 'setting_company_*',
        '/^rate_limiter-httpapi:.*/' => 'rate_limiter-httpapi:*',
        '/^filters_.*/' => 'filters_*',
        '/^process_model_observer_.*/' => 'process_model_observer_*',
        '/^application_setStoredSession_.*/' => 'application_setStoredSession_*',
        '/^application_getStoredSession_.*/' => 'application_getStoredSession_*',
        '/^application_payday_.*/' => 'application_payday_*',
        '/^application_campaign_.*/' => 'application_campaign_*',
        '/:\d+/' => ':*',
    ],
],
```

Could become...

```php
Recorders\CacheInteractions::class => [
    'enabled' => env('PULSE_CACHE_INTERACTIONS_ENABLED', true),
    'sample_rate_schedule' => true,
    'sample_rate' => [[
        'start_hour' => 9,
        'sample_rate' => env('PULSE_CACHE_INTERACTIONS_SAMPLE_RATE', 0.025),
    ], [
        'start_hour' => 17,
        'sample_rate' => env('PULSE_CACHE_INTERACTIONS_SAMPLE_RATE', .8),
    ]], [
        'start_hour' => 20,
        'sample_rate' => env('PULSE_CACHE_INTERACTIONS_SAMPLE_RATE', 1),
    ]],
    'ignore' => [
        ...Pulse::defaultVendorCacheKeys(),
    ],
    'groups' => [
        '/^job-exceptions:.*/' => 'job-exceptions:*',
        '/^health:checks:.*/' => 'health:checks:*',
        '/^laravel-health:check-.*/' => 'laravel-health:check:*',
        '/^dashboard_stats_.*/' => 'dashboard_stats_*',
        '/^archive:db:.*/' => 'archive:db:*',
        '/^setting_company_.*/' => 'setting_company_*',
        '/^rate_limiter-httpapi:.*/' => 'rate_limiter-httpapi:*',
        '/^filters_.*/' => 'filters_*',
        '/^process_model_observer_.*/' => 'process_model_observer_*',
        '/^application_setStoredSession_.*/' => 'application_setStoredSession_*',
        '/^application_getStoredSession_.*/' => 'application_getStoredSession_*',
        '/^application_payday_.*/' => 'application_payday_*',
        '/^application_campaign_.*/' => 'application_campaign_*',
        '/:\d+/' => ':*',
    ],
],
```

Behind the scenes you could pull out array items and check whether the current hour is equal or greater than the defined hour. To keep things simple, don't specify minutes or seconds, this means it would always go forward.

**Comment by JoshuaRobertson** [comment] 2024-02-05 16:23
This would be a useful for a similar project I'm working on too.

**Comment by timacdonald** [comment] 2024-02-12 03:06
Pulse always resolves the sample rate from the config repository. This means that you could manually adjust the sample rate on incoming requests and it should be respected.

```php
// AppServiceProvider

public function boot()
{
    if (now()->hour >= 17) {
        $sampleRate = 0.8;
    } else if (now()->hour >= 9) {
        $sampleRate = 0.025;
    } else {
        $sampleRate = 1.0;
    }

    foreach (Config::get('pulse.recorders') as $class => $config) {
        Config::set("pulse.recorders.{$class}", [...$config, 'sample_rate' => $sampleRate]);
    }
}
```

I haven't tested the above, but it should do the trick.

**Comment by timacdonald** [comment] 2024-02-12 03:06
Will close this as it is a feature request and not a bug.

**Closed as completed by timacdonald** 2024-02-12 03:06 UTC
Labels: needs more info
