### ISSUE TITLE
PlanetScale deploy requests fail due to missing unique keys

### ISSUE THREAD

**Issue by JoeyMckenzie** [laravel/pulse#136] opened 2023-12-04 19:15 UTC
### Pulse Version

1.0@beta

### Laravel Version

10.10

### PHP Version

8.3

### Description

Using PlanetScale, I was unable to apply migrations to the production branch due to missing unique keys. Was able workaround this by adding a `$table->bigIncrements('id')` to each pulse table definition, though I'm not sure if that's intended in the case these are meant to be key-less tables or identified by the various indexes on each table.

I'm fairly new to Laravel, so I'm not too sure if this is really a pressing issue. Applying the keys manually seems to fix the issue.

![image](https://github.com/laravel/pulse/assets/16873254/c776edb5-234b-4ed4-8269-614562f1c115)

### Steps To Reproduce

- Create new Laravel application use the `mysql` connector
- Connect to PlanetScale, create a `dev` branch off `main`
- Apply migrations locally
- Create a deploy request to merge `dev` changes into `main`

**Comment by toitzi** [comment] 2023-12-04 19:41
I think this is the same as #108 maybe you can workarround it till the original issue is resolved / has a solution

**Comment by JoeyMckenzie** [comment] 2023-12-04 20:17
Figured that might be the case. Easy enough to work around in the case of PlanetScale, working as expected with just those few changes. Thank you for taking a look!

**Comment by timacdonald** [comment] 2023-12-05 05:58
Duplicate of https://github.com/laravel/pulse/issues/108

**Closed by timacdonald** 2023-12-05 05:58 UTC
