### ISSUE TITLE
 Unknown column 'name' in 'field list'

### ISSUE THREAD

**Issue by nezaboravi** [laravel/pulse#189] opened 2023-12-08 06:40 UTC
### Pulse Version

1.0.0

### Laravel Version

10.4.2

### PHP Version

8.2

### Livewire Version

3

### Description

VIsiting pulse dashboard getting error:
 Unknown column 'name' in 'field list'
 
 This error is caused by public function resolveUsers()
 
<img width="778" alt="image" src="https://github.com/laravel/pulse/assets/1515172/266b765f-db4d-41d5-aef9-c5314140504a">

I do not have name column in users table. 
I have a Attribute created tho, but this does not solves the problem.

What is possible solution? 

Thank you <3

### Steps To Reproduce

Fresh installation and no special steps except that database does not have name column, but first_name and last_name instead :)

**Comment by jessarcher** [comment] 2023-12-08 06:44
Hey @nezaboravi,

This looks like a duplicate of #109.

You should be able to customize this with the `Pulse::users` method: https://laravel.com/docs/10.x/pulse#application-usage-card

**Closed by jessarcher** 2023-12-08 06:44 UTC
