### ISSUE TITLE
Can we get the guard name in Pulse::users()  ?

### ISSUE THREAD

**Issue by AlexDanault** [laravel/pulse#139] opened 2023-12-04 21:19 UTC
In a bunch of apps I have two distinct sections (public and admin) with totally different user classes (users and admins) but all we have in Pulse::users() as id's , but those are not enough to distinguish one from another, as both tables will have a user # 1.

**Comment by timacdonald** [comment] 2023-12-05 05:31
Duplicate of https://github.com/laravel/pulse/issues/121

**Closed by timacdonald** 2023-12-05 05:31 UTC
