### ISSUE TITLE
Dashboard in the browser is very slow

### ISSUE THREAD

**Issue by incon** [laravel/pulse#160] opened 2023-12-06 06:37 UTC
### Pulse Version

1.0.0-beta5

### Laravel Version

10.35.0

### PHP Version

8.2.13

### Database Driver & Version

MySQL 8.0.33 (DBnign)

### Description

Dashboard is very slow when updating and resizing the window.

https://web.dev/articles/avoid-large-complex-layouts-and-layout-thrashing?utm_source=devtools#avoid-forced-synchronous-layouts

<img width="704" alt="Screenshot 2023-12-06 at 2 26 29 pm" src="https://github.com/laravel/pulse/assets/405629/fd888af7-3f6c-42ca-9c43-d47302fa3bfa">

### Steps To Reproduce

Wait for an update or resize the browser window.

**Comment by jessarcher** [comment] 2023-12-06 06:49
I'm having trouble replicating this one.

I recorded and let it run for just over 15 seconds to capture a few updates.

![image](https://github.com/laravel/pulse/assets/4977161/3f333920-247a-4187-b481-4f548ebb9188)

If I resize the window constantly while recording then I can get the rendering and painting numbers up, but I assume that's to be expected as I'm forcing it to constantly re-render for the duration of the recording.

**Comment by incon** [comment] 2023-12-06 07:12
Chrome Version 120.0.6099.62 (Official Build) (arm64)
Apple M2 Max

https://github.com/laravel/pulse/assets/405629/ef4756f3-65da-4dfe-a195-192702a81ef5

**Comment by timacdonald** [comment] 2023-12-07 02:12
Wonder if this is related to the SQL syntax highlighting.

@incon do you have a bunch of queries in the slow queries table? If you remove some does it improve in speed? If you only have one is it _better_, and if have none is it fast again?

**Comment by jessarcher** [comment] 2023-12-12 23:29
#172 is released now. Feel free to re-open if there are still issues :+1:

**Comment by incon** [comment] 2023-12-13 09:23
While much improved with `PULSE_SLOW_QUERIES_HIGHLIGHTING=false` it's still slow.

**Comment by timacdonald** [comment] 2023-12-13 23:54
@incon do you have a bunch of queries in the slow queries table? If you remove some does it improve in speed? If you only have one is it better, and if have none is it fast again?

**Comment by incon** [comment] 2023-12-14 00:39
@timacdonald Removing them makes the dashboard fast again.

**Comment by crynobone** [comment] 2023-12-14 01:27
https://github.com/laravel/pulse/blob/9eda727da25be60c838fb604daced2073c1607fd/config/pulse.php#L191C1-L200C11

@incon did you also update the `config/pulse.php` containing the new options?

**Comment by incon** [comment] 2023-12-14 01:41
#227 While in local development with a low threshold. I ended up with lots of telescope entries in the slow queries table. This made the dashboard very slow with over 1000 slow quires. 

It would nice if slow queries could be aggregated based on the SQL prepare statement.

**Comment by jbrooksuk** [comment] 2023-12-14 09:22
@incon thanks for the PR. Just to confirm, are you saying that the Telescope queries are the issue here?

**Comment by incon** [comment] 2023-12-14 09:44
In this case yes, but the issue is displaying the 1000 slow quires all at once if you have that many slow queries.

**Comment by timacdonald** [comment] 2023-12-14 21:45
@incon that is interesting. It should have limited the slow queries to only show `100` at most on the dashboard.

We will have to take a look at that.

**Comment by timacdonald** [comment] 2023-12-15 04:32
I'm not able to reproduce this on a fully filled dashboard, i.e., where all tables have the max of 100 items each.

We might close this and if we hear others are having issues we can dig in. Obviously happy for a fix if we can come up with one.

**Closed by timacdonald** 2023-12-15 04:32 UTC
Labels: bug, needs more info
