### ISSUE TITLE
Could not find Livewire component in DOM tree

### ISSUE THREAD

**Issue by xHeaven** [laravel/pulse#91] opened 2023-12-01 22:13 UTC
### Pulse Version

v1.0.0-beta2

### Laravel Version

10.34.2

### PHP Version

8.3.0

### Description

For some reason, I'm getting "Could not find Livewire component in DOM tree" in my Laravel project with Pulse freshly installed into it.

![image](https://github.com/laravel/pulse/assets/14284867/4de53b86-3c7c-432e-a792-be49ef4e68a1)

The /pulse endpoint somewhat loads with the informations, but the interface itself is unresponsive (selectors, etc).

Where should I even start to debug this?

### Steps To Reproduce

-

**Comment by toitzi** [comment] 2023-12-01 22:21
Hm, hard to track down, there seems to be a issue with livewire that causes this - which could potentially be your issue. Some reports i found to say it is fixed and some reports it is not, can you check which exact version of livewire you are using? Maybe just for a quick test, can you edit your config/livewire.php and set "`inject_morph_markers`" to `false` and see if that changes anything for you?

**Comment by xHeaven** [comment] 2023-12-01 22:31
> Hm, hard to track down, there seems to be a issue with livewire that causes this - which could potentially be your issue. Some reports i found to say it is fixed and some reports it is not, can you check which exact version of livewire you are using? Maybe just for a quick test, can you edit your config/livewire.php and set "`inject_morph_markers`" to `false` and see if that changes anything for you?

My project itself doesn't use Livewire - however, since Pulse required it as a dependency, it's definitely there in my packages.
I'm on `v3.2.2` with Livewire right now. I also published its config file and set `inject_morph_markers` to `false`, but everything stayed the same. (even the `morph` and `morph2` calls in the error stacktrace, not sure if they should even disappear though)

I've checked a few forums related to this issue, but none of those fixes seemed to solve the issue.
Also, a colleague of mine reported that it's working on his Mac - but it's not working for me, nor in our production environment. I find this odd, because we are in a dockerized context and also git versioned, so pretty much everything should be the same for us.

Any other tips? Appreciate the help.

**Comment by xHeaven** [comment] 2023-12-02 20:14
> Hi, Can you please paste the output of `php artisan about` ?

Absolutely, see below.
```
root@1f038123270f:/var/www# php artisan about

  Environment ......................................................................................................................................  
  Application Name .................................................................................................................... MyLaravelApp  
  Laravel Version .......................................................................................................................... 10.34.2  
  PHP Version ................................................................................................................................ 8.3.0  
  Composer Version ........................................................................................................................... 2.6.5  
  Environment ................................................................................................................................ local  
  Debug Mode ............................................................................................................................... ENABLED  
  URL ............................................................................................................................. mylaravel.app  
  Maintenance Mode ............................................................................................................................. OFF  

  Cache ............................................................................................................................................  
  Config ................................................................................................................................ NOT CACHED  
  Events ................................................................................................................................ NOT CACHED  
  Routes ................................................................................................................................ NOT CACHED  
  Views ..................................................................................................................................... CACHED  

  Drivers ..........................................................................................................................................  
  Broadcasting ................................................................................................................................. log  
  Cache ...................................................................................................................................... redis  
  Database ................................................................................................................................... mysql  
  Logs ....................................................................................................................................... daily  
  Mail ........................................................................................................................................ smtp  
  Queue ...................................................................................................................................... redis  
  Session .................................................................................................................................... redis  

  Livewire .........................................................................................................................................  
  Livewire .................................................................................................................................. v3.2.2
```

**Comment by ysrdevs** [comment] 2023-12-02 20:21
The issue might relate to Livewire not injecting in your pulse dashboard. Let's manually inject it

In your vendor/laravel/pulse/resources/views/components/pulse.blade.php file, could you add @livewireStyles just above the closing </head> tag and @livewireScripts just before the closing </body> tag and refresh the page?

If this does not work, is there a change in your console log?

**Comment by timacdonald** [comment] 2023-12-03 22:27
@xHeave1 

1. Is this app deployed or running locally?
2. If running locally, how are you running it? What OS. Sail, docker, etc.? Provide as much info as possible.
3. If it is deployed, is it wrapped in Cloudflare?

**Comment by timacdonald** [comment] 2023-12-05 23:13
@xHeaven appreciate all this, but we would need it to be a GitHub repository that we can clone down and build that illustrates the issue.

I'll close this one for now, but please reply here if you get a repository that reproduces the issue and we will take a closer look for you.

**Closed by timacdonald** 2023-12-05 23:13 UTC
Labels: help wanted, needs more info

**Comment by timacdonald** [comment] 2023-12-06 21:57
Glad you got it tracked down.
